# SPDX-FileCopyrightText: 2020-2024 The Kazarma Team
# SPDX-License-Identifier: AGPL-3.0-only

version: '3.7'

volumes:
  postgres_files:

services:
  
  kazarma:
    image: registry.gitlab.com/technostructures/kazarma/kazarma:${KAZARMA_VERSION:-latest}
    # ports:
    #   - "4000:4000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=kazarma
      - DATABASE_USERNAME=kazarma
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - HOMESERVER_TOKEN=${HOMESERVER_TOKEN}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - MATRIX_URL=${MATRIX_URL}
      - HOST=${HOST}
      - ACTIVITY_PUB_DOMAIN=${ACTIVITY_PUB_DOMAIN}
      - PUPPET_PREFIX
      - BRIDGE_REMOTE
      - HTML_SEARCH
      - HTML_AP
      - LOG_LEVEL
      - RELEASE_LEVEL
      - SENTRY_ENABLED
      - SENTRY_DSN
      - LOKI_ENABLED
      - LOKI_HOST
      - LOKI_ORG_ID
      - METRICS_ENABLED
      - METRICS_PORT
      - GRAFANA_ENABLED
      - GRAFANA_HOST
      - GRAFANA_TOKEN
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=kazarma
      - POSTGRES_DB=kazarma
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    volumes:
      - postgres_files:/var/lib/postgresql/data
