# SPDX-FileCopyrightText: 2020-2023 The Kazarma Team
# SPDX-License-Identifier: AGPL-3.0-only

version: '3.7'

volumes:
  postgres_files:

services:
  
  kazarma:
    image: registry.gitlab.com/kazarma/kazarma/production:${KAZARMA_VERSION:-latest}
    # ports:
    #   - "4000:4000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=kazarma
      - DATABASE_USERNAME=kazarma
      - DATABASE_PASSWORD
      - SECRET_KEY_BASE
      - HOMESERVER_TOKEN
      - ACCESS_TOKEN
      - MATRIX_URL
      - HOST
      - ACTIVITY_PUB_DOMAIN
      - PUPPET_PREFIX
      - BRIDGE_REMOTE
      - HTML_SEARCH
      - HTML_AP
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=kazarma
      - POSTGRES_DB=kazarma
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    volumes:
      - postgres_files:/var/lib/postgresql/data
