{
 "title": "Kazarma Dashboard",
 "tags": [ "kazarma" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Bridged messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bridged events by room type",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(room_type) (increase(kazarma_events_bridged_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bridged events by event type",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(type) (increase(kazarma_events_bridged_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bridged activities by room type",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(room_type) (increase(kazarma_activities_bridged_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bridged activities by activity type",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by(type, obj_type) (increase(kazarma_activities_bridged_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bridged rooms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Rooms created by type",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(room_type) (increase(kazarma_rooms_created_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Puppets created", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Matrix puppets created",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(kazarma_puppets_created_total{type=\"matrix\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ActivityPub puppets created",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(kazarma_puppets_created_total{type=\"ap\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}